### ISSUE TITLE
Local CA (between hosts)

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#104]
For if we once require a local CA to establish trust between hosts, this _might_ be a starting point: https://github.com/numtide/devshell/pull/74

**Comment by nrdxp** [comment]
Probably best solution https://www.tweag.io/blog/2020-12-16-trustix-announcement

**Comment by blaggacao** [comment]
Another discovery in this problem space: https://github.com/NixOS/nixpkgs/pull/112322
