### ISSUE TITLE
Profiles imports are brittle, causing failure if imported twice

### ISSUE THREAD

**Issue by ymarkus** [divnix/devos#136]
## Expected Behavior
If I set `users.users.<name>.shell` in the `users/<name>/default.nix` file, there should be no conflicts anywhere (happens for any user).

## Current Behavior
Building the system configuration errors out with following:
for `users.users.<name>.shell = pkgs.zsh`:
```
The unique option `users.users.<name>.shell' is defined multiple times, in:
 - <unknown-file>
 - <unknown-file>.
```

## Possible Solution

Maybe I have to set it somewhere else? Can't find anything in the documentation...

**Comment by nrdxp** [comment]
I can't reproduce this error in either core or community from a fresh checkout. What revision are you on? The only place I set the default shell for users is: https://github.com/divnix/devos/blob/community/profiles/develop/zsh/default.nix#L9

This doesn't conflict with users.users.<name>.shell though, as I tested it explicitly, and this is only set if your using the community branch and develop or zsh profile. You might want to grep around and see if you accidentally set it twice somewhere, or perhaps this was an issue with an older revision but is now resolved. Worst case scenario, you can always force the setting with `mkForce`.

I'll leave this open for a bit to help you find a solution.

**Comment by ymarkus** [comment]
OK, I've found the error. It seems like if you import a profile twice, it does weird things. Here's what happened:

1. `users.<name>` get imported in core:
```nix
core = [ users.nixos users.root  ];
```
2. `core` gets imported in `graphics`:
```nix
graphics = core ++ [ graphical ];
```
3. `graphics` get imported in `pc` & `gaming`:
```nix
pc = graphics ++ [ develop networking.samba printing systems.pc virt zfs ];
gaming = graphics ++ [ graphical.games ];
```
4. `pc` & `gaming` get imported in `NixOS.nix`:
```nix
imports = [...] ++ suites.pc ++ suites.gaming;
```
So everything in the profiles `core` & `graphical` got imported twice. That's why mkForce also didn't work.

Maybe a hint in the manual would be fitting if this is the case?

**Comment by nrdxp** [comment]
Good catch, we don't want this biting us in the future. Perhaps the profiles attribute set in suites should just contain paths to the profile, instead of importing it outright. The default import logic prevents this sort of error when importing the same path twice, so we might want to just leverage that.

**Comment by ymarkus** [comment]
Yeah, I just found out it can also happen when importing a profile inside suites and then importing it inside another profile like this:
```nix
{
  suites = with profiles; rec {
    [...]
    pc = graphics ++ [ develop networking.samba printing systems.pc virt zfs ];

    laptop = pc ++ [ systems.pc.laptop ];
  };
}
```
and `laptop/default.nix`:
```nix
{
  imports = [
    ../. # this imports pc
  ];
}
```

**Comment by ymarkus** [comment]
Thanks, seems to work now!
