### ISSUE TITLE
nixos-option no longer works after collect garbage

### ISSUE THREAD

**Issue by liaowang11** [divnix/devos#138]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
`nixos-option` from `profile/core/default.nix` should still works after `nix-collect-garbage -d`
`profile/core/default.nix` includes an alias to fix `nixos-option`:
```
nixos-option = "nixos-option -I nixpkgs=${toString ../../compat}";
```

## Current Behavior
`nixos-option` :
```
terminate called after throwing an instance of 'nix::EvalError'
  what():  cannot import '/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source/flake.nix', since path
 '/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source' is not valid, at /nix/store/2mpgi4bvn8py4liv9
w3mjxd2c5r7bvv8-source/default.nix:131:19
fish: Job 1, “command nixos-option -I nixpkgs…” terminated by signal SIGABRT (Abort)
```

## Possible Solution
The nixpkgs used by `flake-compat` in `compat/default.nix` has no referrers, which is why it’s got garbage collect.
I don’t know enough of Nix to add some kind of references to the `nixpkgs source` to fix this. 

## Steps to Reproduce
1. nixos-rebuild switch
2. nix-collect-garbage -d
3. nixos-option errors

## Context
nixos-option use `/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source/`
which is included in gc print-dead.
```shell
> nixos-option services.earlyoom                                   
unpacking 'https://github.com/edolstra/flake-compat/archive/99f1c2157fba4bfe6211a321fd0ee43199025dbf.tar.gz'...
terminate called after throwing an instance of 'nix::EvalError'
  what():  cannot import '/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source/flake.nix', since path
 '/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source' is not valid, at /nix/store/2mpgi4bvn8py4liv9
w3mjxd2c5r7bvv8-source/default.nix:131:19
fish: Job 1, “command nixos-option -I nixpkgs…” terminated by signal SIGABRT (Abort)

> nix-store -q --references /nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source

> nix-store --gc --print-dead | rg /nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source
finding garbage collector roots...
removing stale link from '/nix/var/nix/gcroots/auto/xmssbbj2d1pfm51cqci88ggxnmi3j9dj' to '/tmp/nixos-rebuild.CRuJ2V/result'
determining live/dead paths...
/nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source
```

**Comment by nrdxp** [comment]
I can't reproduce this. IIRC, I found this issue myself, and I believe the `toString` fixed it. Here's what happens on my machine:
[![asciicast](https://asciinema.org/a/YvVmJl9S4QPuHAm5oVNcKvz0y.svg)](https://asciinema.org/a/YvVmJl9S4QPuHAm5oVNcKvz0y)

**Comment by liaowang11** [comment]
@nrdxp So what is currently referring that `nixpkgs` which nixos-option is using?
On my two machines, all no referrers(the store path may varies).
❯ nix-store -q --referrers /nix/store/slf28rxb23rmx2qgid4bwfifwbkyb5ji-dxl4kb7jclicnk2mignizz53bk8wl9z4-source

**Comment by nrdxp** [comment]
```console
❯ alias nixos-option
nixos-option='nixos-option -I nixpkgs=/nix/store/1ivyv4zwqzqjpqz5qb0yp9xbax331m6l-source/compat'
```

**Comment by liaowang11** [comment]
Ok, i will dive into this further, close for now.

**Comment by nrdxp** [comment]
I will also take a closer look later as well by clearing all non declarative gcroots and see if maybe the issue will arise then.
