### ISSUE TITLE
greetd minimalism

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#153]
## Ideas
The below triplet is a really refreshing extremely minimal greeter solution written in rust, that I'd like to adopt in my environments. I might eventually get around and package them myself, but if somebody is interested in beating me to it, it will be an easy win. :smile: 

## Requests
- https://sr.ht/~kennylevinsen/greetd/
- https://git.sr.ht/~kennylevinsen/wlgreet
- https://github.com/apognu/tuigreet

**Comment by Th3Whit3Wolf** [comment]
All of these and more are now available on unstable

**Comment by Narice** [comment]
@blaggacao Can the unstable modules be imported as supplementary modules to complement the stable ones?

**Comment by blaggacao** [comment]
@Narice You would be pulling the corresponding packages in `./overlays.overrides.nix`, as for the modules, you can use `latestModulePath` which is an automagic `specialArgs` in `fup` for the input channel named `latest`. So to pull in modules, it would be something like:

```nix
{latestModulePath}: {
    imports = [ "${latestModulePath}/path/to/module.nix" ];
}
```
it can be that you also need to disable some current stable module with [`disabledModules`](https://nixos.org/manual/nixos/stable/index.html#sec-replace-modules) if there are conflicts. Not always are those modules compatible tough, so chances are somewhat 50/50.


[fup-implementation](https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/6b2ea4b02cad77fac581c6a9ec4f822ba87dce5c/lib/systemFlake.nix#L144-L152) for reference.

Let me know how it goes. :wink:

**Comment by Narice** [comment]
Nice, Thanks!
Do you think we can close this issue?

**Comment by Pacman99** [comment]
Yeah I don't think we should encourage module creation or packaging _in_ this repo anyways, since the whole point is to put them in your devos flake and share it.
Maybe we can create some tag for thread in GH discussions where you can share links to your content or requests for packaging/modules from others.
