### ISSUE TITLE
using cookiecutter or similar tools to bootstrap the template

### ISSUE THREAD

**Issue by jnoortheen** [divnix/devos#16]
**Is your feature request related to a problem? Please describe.**
As of now we endup with lot of files not necessarily used. 

**Describe the solution you'd like**
Using such tool we can set the 
 - default user name
 - new-host file's name -> automatically generate the file under hosts folder after entering the name as from generate-config 
 - set of profiles that user wants to use
 - desktop environment that user wants
 - etc.,
 - an update script to pull down latest changes from this repo

**Comment by nrdxp** [comment]
I've got some ideas for making the bootstrap process simpler and more automatic and this could definitely be a part of it. It'll take some time, but I'll have a new branch up soon with some new ideas. I'll see if I can work this in.

**Comment by nrdxp** [comment]
I've decided not to opt for external tools, but instead I created a [bare](https://github.com/nrdxp/nixflk/tree/bare) branch which should suffice if you're wanting the benefits of this template without any of the predefined profiles. I've also wired up the template output, so creating a new iteration of a bare template is as simple as:
```
nix flake new -t "github:nrdxp/nixflk/bare" flk
```

**Comment by nrdxp** [comment]
I'm reopening this, as we might be able to use cookie-cutter during the building of the system generation to easily solve some current introspective problems, such as knowing available users to assign user properties to each, without causing infinite recursion. Not to mention, cookie cutter or similar tools could help with #179 in general.

**Comment by blaggacao** [comment]
I'd have thought ideally nix templates would offer us something, here.

**Comment by blaggacao** [comment]
> When running `nix edit nixpkgs#hello`, there is a heuristic to find the package declaration which essentially goes like this:

> ```
$ nix repl Welcome to Nix version 3.0pre20200829_f156513. Type :? for help. nix-repl> pkgs = import <nixpkgs> {} nix-repl> builtins.unsafeGetAttrPos "description" pkgs.hello.meta { column = 5; file = "/home/zimbatm/go/src/github.com/NixOS/nixpkgs/pkgs/applications/misc/hello/default.nix"; line = 15; } 
```

> Once the file and line have been found, call `$EDITOR $file +$line`.

> Here is what happens when an attribute cannot be found:

> ```
nix-repl> builtins.unsafeGetAttrPos "broken" pkgs.hello.meta null 
```

> It wouldn’t be too hard to write a tool that relies on this information and then combines it with an AST patcher. We have a number of those in the community.

Quote from zimbatm from a private conversation.

**Comment by blaggacao** [comment]
With suites, we have a cheap way of introspecting the global composing components for a host by name and coukd write those into a host template via `substitute --replace '@suites@' "${suiteNames}"`.

That could go into `flk up` which already partly addresses this use case.

**Comment by blaggacao** [comment]
This template has evolved quite a bit, and also `flk` gained a boostrapping command. I don't think there is a need to improve the templating experience further.
