### ISSUE TITLE
fix lib docs

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#166]
@blaggacao 

Following restructuring of `./lib` and discussion in https://github.com/divnix/devos/pull/161#pullrequestreview-611736151, this is on my TODO list.

**Comment by Pacman99** [comment]
lib docs will need some updating after #264 the multi-arch info and a few other things aren't true anymore. But hopefully mkFlake optionsDoc should cover a lot of the documentation needs.

**Comment by Pacman99** [comment]
Updated some docs in https://github.com/divnix/devos/pull/264/commits/ffe4836e35e8b4a1ef2d99292c1ea4a3df6ad821. So the doc folder is mostly accurate with the new template and api. It could probably use some more work though.

**Comment by blaggacao** [comment]
ok thanks! I'm going to close this.
