### ISSUE TITLE
doc: quickstart "ISO. What next?"

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#167]
Given one started to plan an environment with devos:

There is a bit of a gap between flashing the ISO of a new host onto a stick and fully managing a host either locally (after having set up network and access rights and cloned the repo onto it) or remotely via deployrs (after having bootstrapped identity and ssh access).

Related: https://github.com/divnix/devos/issues/132#issuecomment-799016542

documenting my journey so far:

1. `flk iso MyNewHost`
2. `dd ...`
3. boot into iso on target host
4. follow https://nixos.org/manual/nixos/stable/index.html#sec-installation-partitioning
5.  1), 2) & 3) of https://nixos.org/manual/nixos/stable/index.html#sec-installation-installing, that is: 
  - `mount /dev/disk/by-label/nixos /mnt`
  - `mkdir -p /mnt/boot`
  - `mount /dev/disk/by-label/boot /mnt/boot`
  - `swapon /dev/sda2`
6. keep target running off of the usb memory card
7. from original machine: `deploy ".#MyNewHost" --hostname 192.168.191.179 --ssh-user nixos` & that failed, presumably because according to nixos installer things are to be mounted under `/mnt`

**Comment by blaggacao** [comment]
Maybe we should copy over the current local `devos` repo [onto the iso image](https://github.com/NixOS/nixpkgs/blob/63a9f162355ec84c423690869a97848d73409fb8/nixos/modules/installer/cd-dvd/iso-image.nix#L458-L477) like so:
```nix
    isoImage.contents =
      [
        { source = self;
          target = "/devos/"; # or self.name (if that was to exist)
        }
      ];
```
next to : https://github.com/divnix/devos/blob/d7f15a664d20de910611a29167107aee8ff0dbab/lib/devos/devosSystem.nix#L15

Maybe even a little more magic can be done so that the flk command proper is available on a live cd... That would be really cool.

Off topic:
[Do we have a branded splash image?](https://github.com/NixOS/nixpkgs/blob/63a9f162355ec84c423690869a97848d73409fb8/nixos/modules/installer/cd-dvd/iso-image.nix#L514-L522)

**Comment by Pacman99** [comment]
Somewhat unrelated, but if I created an iso from my server's config which has random systemd services(minecraft, matrix, ...). Will those services startup when I boot from the iso? Because it would be really annoying if a bunch of services starting setting up databases and taking up ram while I'm running through the install. But I still want those applications to exist for easy installation.

**Comment by blaggacao** [comment]
> Will those services startup when I boot from the iso? 

Yes. And indeed that is something that needs more thought, still.

**Comment by Pacman99** [comment]
Perhaps as you add the devos source you could remove the `modules ++` line. And maybe just add self.packages to environment.systemPackages. Not entirely sure what the best solution is. And I think it should be clarified what the goal of isoConfig is, is it purely for installation? or is there more that needs to be accomplished.

**Comment by blaggacao** [comment]
This is gold price input. Let's safe it for a follow up issue / pr though.

**Comment by Pacman99** [comment]
Really looking forward to being able to easily build ISO's for bootstrapping a machine!
