### ISSUE TITLE
Pass 'self' to lib

### ISSUE THREAD

**Issue by Pacman99** [divnix/devos#169]
For os.mkPkgs and os.mkPackages, self is passed to them as a function argument. But why not just pass self to lib/default.nix and make it available for all lib functions? 
So you can just call `os.mkPkgs` without any arguments. And `os.mkPackages` can just be passed `pkgs`.

**Comment by blaggacao** [comment]
I would be somehow in [favor of this](https://github.com/divnix/devos/pull/168#discussion_r594040001).

**Comment by Pacman99** [comment]
Yup your PR was what gave me the idea, and I think it would simplify some other lib functions as well.

**Comment by nrdxp** [comment]
I've thought about this as well. Was also wondering if passing self as a specialArg would be useful in general. If we do this, we should probably do that as well. Although, for clarity we should probably rename it on passing, something like:
`{ devos = self; }`

**Comment by Pacman99** [comment]
Thats a good idea. If you do that I'll drop the multiPkgs module argument. Since you could just use `self.packages.system` instead. 

And actually it could obsolete the hosts module arg since other configs could be accessed with self.nixosConfigurations. But I'm not sure since hosts is still easier to access and could prevent possible infinite recursion errors.

**Comment by nrdxp** [comment]
We'll probably want to levarage the new test infrastructure to ensure there is no infinite recursion.

**Comment by Pacman99** [comment]
closed by #168
