### ISSUE TITLE
Help adding easy-hls-nix to devos

### ISSUE THREAD

**Issue by codygman** [divnix/devos#174]
I think I might need to wait for either #jkachmar/easy-hls-nix#3 or #127 for this? I made an attempt adding easy-hls-nix to devos like so:

https://github.com/codygman/devos/commit/a15969dd54059a40a7a31f5658463c7b323cede0

I saw evidence it installed things but `haskell-language-server` was not available. I'm just working around it for now by installing via the quickstart nix expression on that readme but it would be nice to know how to pull things in like that repo.

**Comment by Pacman99** [comment]
If its just the package you want to add, you can add it in extern/default.nix. Take a look at how deploy-rs is added, and do something similar. And if you want it in the devshell you can then add it to the packages list within shell/default.nix.

**Comment by nrdxp** [comment]
Additionally, I'm gonna be upgrading the base `nixos` flake to nixos-unstable and 20.09 is getting pretty stale as we approach the next release. However I have to work out an issue with the CI runner hercules-ci/hercules-ci-agent#291 before I can push the update.

Once I do though, hls 1.0 is included in the latest master and already wired up as an override.
