### ISSUE TITLE
pin inputs into iso live registry

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#190]
## Would your feature fix an existing issue?
With #168 , devos live iso gains the ability to enter the devos devshell and install through it on the target machine during bootstrapping.

Still, the target machine is fetching all inputs again.

## Describe the solution you'd like
By pinning inputs into the registry:
- the target will probably use them (if lockfile is not present and declares a different sha)
- more importantly, the nix store closures will get copied over (I hope I'm right?) and therefore there is no deed to fetch those files

## Describe alternatives you've considered
n/a

## Additional context
- Suggested by @Pacman99 https://github.com/divnix/devos/pull/168#issuecomment-800420441
- similarily, we might want to find a way to copy the devshell closure to the iso, so that entering the devshell uses the baked in nix store closure.

**Comment by Pacman99** [comment]
Updated code(realized I wrote it wrong):
```nix
nix.registry = mapAttrs (n: v: { flake = ${v}; }) (removeAttrs inputs [ "self" "pkgs" "lib" ]);
```

**Comment by blaggacao** [comment]
I'm going to carv out the `inputs` idea of #164 for the implementation.

**Comment by Pacman99** [comment]
I would say just wait for that PR to get merged

**Comment by blaggacao** [comment]
> I would say just wait for that PR to get merged

I thought: maybe we can unbundle it from the `host` use case, which is not a direct dependency to this issue.

**Comment by Pacman99** [comment]
I just think all those things - self, inputs, and hosts - are all pretty related and it makes sense to consolidate them into one PR. The hosts part was already approved so its not much of a blocker. And its really an extension of passing `self`.

**Comment by blaggacao** [comment]
Are we actually even sure we want to pass `inputs` around?
