### ISSUE TITLE
copy evaluation store paths to iso

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#195]
If you, by-comer, are knowledgeable enough to solve https://github.com/divnix/devos/pull/191#issuecomment-800685936, please do.

The goal is to also copy evaluations into the iso to avoid evaluation times on slow/low resource target machines.

**Comment by Pacman99** [comment]
I'm not sure if I misunderstand this. But no matter how many paths we add to the nix store by default, nix will still have to evaluate the nix expressions to figure out what store path it needs. And so if you're talking about evaluation caching, we would have to copy the evaluation cache sqlite databases which would result in an impure call to a file outside of the flake.

Perhaps we can lobby for a nix function that can evaluate an expression and output the evaluation cache.

**Comment by blaggacao** [comment]
I think you are right. I'll test and report back. But probably you are right and my idea in https://github.com/Pacman99/devos/pull/2 is falling short of fixing this.

**Comment by Pacman99** [comment]
I mean copying the drvPath is definitely an improvement. I assume it takes nix less time to get to the drv path than evaluate and get the store path.

**Comment by blaggacao** [comment]
For lack of traction, for the te being I withdrawing from this issue.
