### ISSUE TITLE
nix is built two times

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#203]
1. `nix develop` &rarr; `nix` is built (+15 min)
2. `flk iso NixOS` &rarr; (same?) `nix` is built _again_ (+15 min)

**Comment by Pacman99** [comment]
Its likely because of the custom patches to nixUnstable. I think the current state of #192 removes that so nix will just be pulled from binary cache for both. But thats also introducing other problems.

**Comment by nrdxp** [comment]
Can we close this?
