### ISSUE TITLE
flk install broken since 3 days worth of nix update

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#204]
https://github.com/NixOS/nix/issues/4613#issuecomment-802917132

https://github.com/NixOS/nixpkgs/blob/e30d87f22237fe25618136eb9f818ecefaeb02a9/nixos/modules/installer/tools/nixos-install.sh#L128

`nix flake info` -> `nix flake metadata`

Until upstream implements an anti corruption layer, it seems we are left with the task to do so.

Upstream Issue: https://github.com/NixOS/nix/issues/4613#

EDIT: just changing `flake info` -> `flake metadata` works. I tested it super-manually on my local setup, but have no idea how to properly wire this up in here (as an overlay?).

**Comment by blaggacao** [comment]
Was closed by https://github.com/NixOS/nixpkgs/pull/116807

**Comment by nrdxp** [comment]
So can we close this issue then?

**Comment by blaggacao** [comment]
I think, by an `nixpkgs` update to the flake.lock file, yes.

**Comment by codygman** [comment]
How can one manually update? For instance I'm getting:

```
[devshell]$ flk razer switch
[sudo] password for cody: 
error: 'info' is not a recognised command
Try 'nix --help' for more information.
```

I see that flk switch is just:

```
sudo nixos-rebuild --flake "$DEVSHELL_ROOT#$1" "${@:2}"
[devshell] shell $ echo $DEVSHELL_ROOT
/home/cody/devos
```
So that gives:

```
sudo nixos-rebuild --flake "/home/cody/devos#razer" "${@:2}"
```

I think this:

```
[devshell]$ sudo nixos-rebuild --flake "/home/cody/devos#razer" switch
error: 'info' is not a recognised command
Try 'nix --help' for more information.
```

So... nixos-rebuild is broken for me? I think I can do a build and then switch to it in this case maybe? I'm not totally sure how to get out of this state.

**Comment by Pacman99** [comment]
Yeah I think there was a PR merged to update nixUnstable which now has a deprecated alias for `nix flake info`. As a workaround I believe you can do `nix build /home/cody/devos#nixosConfigurations.razer` then `./result/bin/switch-to-configuration switch`.

**Comment by nrdxp** [comment]
If the update broke `nixos-rebuild` for everyone, perhaps we should reprogram _flk.sh_ to run `nix shell ".#nixosConfigurations.${name}.config.system.build.toplevel" -c switch-to-configuration OPTION`

**Comment by blaggacao** [comment]
Looks like it pays out well to have a `flk` wrapper. :+1:

**Comment by ymarkus** [comment]
If someone is looking for a workaround for `nixos-install`, you can run the following cmd to patch it:
`cp $(which nixos-install) . && sed -i 's@flake info@flake metadata@' ./nixos-install`

**Comment by blaggacao** [comment]
This was a temporary issue.
