### ISSUE TITLE
Cachix caches aren't added to the configuration

### ISSUE THREAD

**Issue by Pacman99** [divnix/devos#208]
I'm not sure if I'm missing something, but I can't seem to find anywhere where cachix is included in the nixos configurations.

## Expected Behavior
Building a host with devos should have the cachix binary caches included.

## Current Behavior
Cachix is available in the cachix folder, but isn't wired up to be a part of the host.

## Possible Solution
import `cachix.nix` somewhere in `hosts/default.nix`

## Context
This could be intentional, I'm not sure but I can't find a reason for why it was removed.

**Comment by nrdxp** [comment]
must've been removed by mistake, definitely not intentional.
