### ISSUE TITLE
`pathsToImportedAttrs` does not accept directories

### ISSUE THREAD

**Issue by GTrunSec** [divnix/devos#221]
Does anyone import the modules more than one in `module-list.nix`. But for me, only one module can be loaded in configuration which in the first line.

this issue appeared in https://github.com/GTrunSec/nixos-flk/tree/core/modules '

migrated from https://github.com/GTrunSec/nixos-flk/tree/master/modules (old version of nixflk)

**Comment by GTrunSec** [comment]
I did a patch here https://github.com/GTrunSec/nixos-flk/commit/b78f36c9072a31151a56405329a5111217e8f514#diff-fbc6c1d4c3b6db8fb54278582eb1d965ed644e97509e130346ae130da5406cb3. it works well for me.

**Comment by Pacman99** [comment]
I think that might be because devos requires each module to be a specific file. And not a default.nix in a directory. Thats how its able to export modules under `nixosModules`, it gets the name from the file by stripping the '.nix'. But this could definitely be improved, so thanks for opening this.

**Comment by nrdxp** [comment]
I think, if it is a directory, we can use probably use `baseNameOf (basNameOf path)` to get it.

**Comment by Pacman99** [comment]
Yeah, should we also cover the case of importing a folder's default.nix?
