### ISSUE TITLE
Providing an interface to nixpkgs.config

### ISSUE THREAD

**Issue by fuzzypixelz** [divnix/devos#237]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Would your feature fix an existing issue?

I recently needed to set `nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;` and the only way I _think_ that can be done (correct me if I'm wrong) is modifying lib/default.nix, specifically the `pkgImport` function.

This is also where `allowUnfree = true` is set (I'm all for sane defaults, but this is very implicit).

## Describe the solution you'd like

Maybe collect `nixpkgs.config from within the `nix` folder? I'm not very familiar with the structure of devos so I can't say many things (again, this might be a non-existent issue and I don't know how it's done)

## Additional context

No. I don't think so.

See https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/browsers/firefox/wrapper.nix#L56
for example. There are many useful (and often necessary) options you might want to set.

I for example needed to activation KDE framework integration in firefox, something that nixos modules can't do (a different build is needed).

**Comment by blaggacao** [comment]
> This is also where allowUnfree = true is set (I'm all for sane defaults, but this is very implicit).

This is a huge issue, indeed. It is being worked on in the context of #232

**Comment by blaggacao** [comment]
This is going to be solved in `api-next` branch which exposes `hostDefaults.config` or `host.config`.


In an effort to clean up issues, I'm going to close this
