### ISSUE TITLE
How to get Started?

### ISSUE THREAD

**Issue by d4hines** [divnix/devos#274]
Hi!
I'm a Nix and NixOS novice but I'm very intrigued by devos and the idea of "standard issue" operating systems and dev environments (especially if they could be automated as WSL VM's). But I'm having a bit of trouble getting started on my (bare metal) NixOS 20.09 installation.

I assumed that if I follow the instructions at https://devos.divnix.com/start/index.html that... well, I'm not sure what will happen actually, but I was hoping it would be obvious when I got there :sweat_smile: 

But instead I get the following:
```sh
$ nix-shell https://github.com/divnix/devos/archive/core.tar.gz -A shell --run "flk get core"
unpacking 'https://github.com/divnix/devos/archive/core.tar.gz'...
error: opening file '/nix/store/0b66qq08r921pbr40qrajidqqsknh3gs-xscreensaver.pam.lock': Permission denied
(use '--show-trace' to show detailed location information)
```

When I run the same command with `sudo` I apparently run out of memory
```
sudo nix-shell https://github.com/divnix/devos/archive/core.tar.gz -A shell --run "flk get core"
[sudo] password for d4hines: 
warning: dumping very large path (> 256 MiB); this may run out of memory
error: out of memory
```
(this machine has 64GB of memory :thinking:)

Then I had a big-brain moment: this is Nix, and there's a `default.nix` file in the root, so I should be able to just clone it and build it, ya? But alas, I get different errors depending on what I try. From my default nix-shell, I cloned the repo, and ran `nix-shell` and I was greeted with `🔨 Welcome to devshell`, which was a good sign!

`flk up` worked. However, `flk nixos switch` gave the the following error output:
```
[sudo] password for d4hines: 
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
```

That's _very_ discouraging, as the whole point of trying out Nix was to avoid issues like this. Nonetheless, I will keep trying! On a hunch, I tried removing all references to `experimental-features` in the repo, but this had no effect.

Any help would be greatly appreciated!

**Comment by Pacman99** [comment]
`flk get core` doesn't work for me either - I've never actually used it before:
```
error (ignored): error: creating file '/nix/store/add-171757-0/x/.links/0zbhlnbw9j58ixrv90cnifdd2nk2ivcjkf8a288icdxi25kvj5hj': No such file or directory
error: getting status of '/nix/store/.links/1b939lzbwi61w706imgfj20i8r7yp23xfrxdds2ghk8fw2jv5a4f': No such file or directory
(use '--show-trace' to show detailed location information)
```
Definitely a bug that we should figure out, or recommend a better method to get started with devos.

I'm not sure whats up with the other issue, if your in the devshell you should be using the same version of nixFlakes as I am and my nix version definitely has that flag. I tried `flk NixOS switch` and that evaluated ok. Make sure you spell the host right, the first argument to `flk` is supposed to be the name of the host file without the `.nix` suffix.

Can you also post the output of `nix --version` your in the devshell.

**Comment by Pacman99** [comment]
Ohh first issue is both of us misunderstanding the `flk get` command: it goes `flk get core [DEST]`, so without the destination I guess the script tries to write to a random folder.

But either way that command is almost the same as cloning the repo, so we need to resolve your second issue, to get you started with flakes.

**Comment by d4hines** [comment]
```
$ nix --version
nix (Nix) 2.3.10

$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.10, channels(d4hines): "home-manager-20.09", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```
Here's my `/etc/nixos/configuration.nix` (it's almost completely vanilla) https://gist.github.com/d4hines/3c9591ab5007bccc1bed69128b62f610

The only thing that stands out to me is the home-manager channel. Still, I thought Nix could pave over all such issues.

**Comment by Pacman99** [comment]
You ran `nix --version` while in the devshell right?

Because thats odd then the devshell didn't override the nix command properly and I'm guessing `--experimental-features` was added in in nix 2.4.

**Comment by d4hines** [comment]
No! I didn't think to do that, woops.

Here's the same from inside devshell:
```
[devshell]$ nix --version
nix (Nix) 2.4pre20210308_1c0e3e4

[devshell]$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.10, channels(root): "nixos-20.09.4038.d90df566caf", channels(d4hines): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

[devshell]$ which nix
/nix/store/2iikmq5ng672s2g938yw0v2zasq2z4z3-devshell-dir/bin/nix

```

**Comment by d4hines** [comment]
And, just to confirm, I'm running `flk NixOS switch` because of  the `./hosts/NixOS.nix` file. I tried `flk up-nixos switch` to see and that didn't work either.

Here's the exact outputs

```
[d4hines@nixos:~/repos]$ git clone https://github.com/d4hines/devos.git
...

[d4hines@nixos:~/repos]$ cd devos/

[d4hines@nixos:~/repos/devos]$ nix-shell 
<big welcome message>

[devshell]$ flk up
writing /home/d4hines/repos/devos/up/nixos/hardware-configuration.nix...
writing /home/d4hines/repos/devos/up/nixos/configuration.nix...
For more hardware-specific settings, see https://github.com/NixOS/nixos-hardware.

[devshell]$ flk NixOS switch
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
```

**Comment by Pacman99** [comment]
So I think I figured it out, it looks like `nixos-rebuild` by default gets hardcoded to a nix path. This gets fixed once you build a system with `nix.package = pkgs.nixFlakes`. But obviously thats not a valid assumption for someone getting started with flakes.

I pushed a possible fix to the `fix-rebuild` branch on this repo. Can you try using that branch and see if your able to rebuild.

**Comment by d4hines** [comment]
So this branch definitely made _more_ progress @Pacman99. Here's what happened:
- I did the same steps as before but on your branch: `nix-shell; flk up; flk NixOS switch;`
- Something happened! I got dropped into a login prompt. Only, the default user login for devos (`nixos` with password `nixos`) didn't work. I logged in with my old username and password and inspected `/etc/nixos/configuration.nix` and indeed, it was my old one.
- Not sure what to expect, I tried rebooting and switching to this new generation. But I got some kind of kernal error, something like:
```
ACPI BIOS ERROR... Failure creating named object /_sb.pcio.g
AE_ALREADY_EXISTS during name lookup
...
timed out waiting for device /dev/disk/by-label/nixos...
```
- I tried going back to the previous generation and this worked. I tried again to see if maybe I had something in the configuration wrong, but I got the same results, only somewhere along the way I seem to have messed up my user profile and can only log in as a root now :( 

Any ideas?

**Comment by Pacman99** [comment]
Yes that seems like the right thing to do. `up-nixos` should include the proper configuration for your filesystems and hardware. It should also include `core` profile which has a good baseline and shell to start from.

Just for organizational purposes, I personally prefer combining all the configs into one file in the hosts directory. If you notice you now also have two files in the `./up` directory. And also you could rename `hosts/up-nixos.nix` to `hosts/<your hostname>.nix`. Just things to consider in the future when your organizing the repository.

**Comment by d4hines** [comment]
Hey! I think it's working! i encountered a lot of weird issues along the way because hardware-configuration.nix was pulling in random docker stuff that was causing boot to fail. But, I have to admit, it's _really_ nice to just switch to a previous generation that works and try to fix it.

My current hurdle is that when I try enabling KDE Plasma as I did before, I just boot into a black screen. How do I enable a desktop with this set up?

**Comment by Pacman99** [comment]
You should be able to enable it like normal: `services.xserver.desktopManager.plasma5.enable`, but I assume thats what you tried.

Did you enable a display manager too? `services.xserver.displayManager.sddm.enable = true`.

**Comment by d4hines** [comment]
This is exactly what I tried (uncommented of course): https://github.com/d4hines/devos/blob/hope/up/nixos/configuration.nix#L49-L50

Also, @Pacman99, you're my hero for walking me through this the last two weeks!

**Comment by Pacman99** [comment]
> This is exactly what I tried (uncommented of course): https://github.com/d4hines/devos/blob/hope/up/nixos/configuration.nix#L49-L50

Just to be clear, `services.xserver.enable = true` was un-commented too right?

Also you might need to set `hardware.opengl.enable = true`.

If that doesn't work, it could be a nixos error, you can try posting an issue upstream. Those are my best guesses for a black screen appearing.

**Comment by codygman** [comment]
> > This is exactly what I tried (uncommented of course): https://github.com/d4hines/devos/blob/hope/up/nixos/configuration.nix#L49-L50
> 
> Just to be clear, `services.xserver.enable = true` was un-commented too right?
> 
> Also you might need to set `hardware.opengl.enable = true`.
> 
> If that doesn't work, it could be a nixos error, you can try posting an issue upstream. Those are my best guesses for a black screen appearing.

Typically when I get a black screen the fix is to add the nvidia driver (if you have an nvidia card).

**Comment by d4hines** [comment]
Hmm. That's good to know, but I have an AMD card. Do I need special drivers for that? I haven't retested this config yet with Pacman's suggestion of `opengl.enable = true` - instead of been using my hobby time to try to get DevOS working with WSL2.

**Comment by d4hines** [comment]
Gonna close this issue now. Thanks for the help all.
