### ISSUE TITLE
default.nix flake-compat is broken

### ISSUE THREAD

**Issue by Pacman99** [divnix/devos#285]
## Expected Behavior
You should be able to use the repo's `default.nix` to access the shell or build your configuration.

## Current Behavior
It gives the following error:
```
error: getting status of '/nix/store/flake.nix': No such file or directory

       … while evaluating 'callLocklessFlake'

       at /nix/store/0n6nqnb6b6cs3hjqprq9k10a1nc2rgiy-source/default.nix:75:23:

           74|
           75|   callLocklessFlake = flakeSrc:
             |                       ^
           76|     let

       … from call site

       at /nix/store/0n6nqnb6b6cs3hjqprq9k10a1nc2rgiy-source/default.nix:173:10:

          172|     if !(builtins.pathExists lockFilePath)
          173|     then callLocklessFlake rootSrc
             |          ^
          174|     else if lockFile.version == 4

       … while evaluating the attribute 'defaultNix'

       at /nix/store/0n6nqnb6b6cs3hjqprq9k10a1nc2rgiy-source/default.nix:182:5:

          181|   rec {
          182|     defaultNix =
             |     ^
          183|       result
```

## Steps to Reproduce

1. Run the recommended command: `nix-shell https://github.com/divnix/devos/archive/core.tar.gz -A shell --show-trace`
2.
3.
4.

## Context

This doesn't affect `shell.nix`. So if you clone the repository and run `nix-shell` that will go directly to `shell.nix` and theres no problem. The issue seems to occur when you use `default.nix`.

cc @narice

**Comment by Pacman99** [comment]
I don't actually know if this is a APIv1 problem, I remember experiencing this a while back. I had assumed it was because of my repository's changes. I didn't realize it was happening to the repo in general

**Comment by Pacman99** [comment]
@narice can you check if #286 fixes the issue for you too? It seems to help for me.

**Comment by Narice** [comment]
Yes! it is building right now ;) awesome work!

**Comment by Narice** [comment]
However I still have an issue after that:
```
fkl get core
error: cannot find flake attribute 'github:divnix/devos/core#defaultTemplate'
```
which is normal as in the flake there is not indeed this attribute, it was commented out during the API update I guess ;)

**Comment by Narice** [comment]
I would really like to help on this as this looks like a trivial thing but I cannot find where the fkl utility is defined x)
It is in this repository?

**Comment by Narice** [comment]
I went full detective mode digga was not named digga before the in-tree lib got removed.
Here is the relevent file: https://github.com/divnix/digga/blob/master/src/pkgs-lib/shell/flk.sh

**Comment by Narice** [comment]
I opened an issue here: https://github.com/divnix/digga/issues/12
