### ISSUE TITLE
flk get core doesn't work anymore

### ISSUE THREAD

**Issue by Narice** [divnix/devos#288]
I am getting the following error:
```
error: cannot find flake attribute 'github:divnix/devos/core#defaultTemplate'
```
the defaultTemplate was commented out for APIv1
here is the line that is more than likely causing the problem:
https://github.com/divnix/digga/blob/24253ba9f44bd82481278a1c4ad691c655a4b283/src/pkgs-lib/shell/flk.sh#L67

**Comment by Pacman99** [comment]
Ohh just saw that you already figured that one out
 > the defaultTemplate was commented out for APIv1

I'm pretty sure that is the problem. flk just tries to init with devos's defaultTemplate - which currently doesn't exist.

**Comment by Pacman99** [comment]
Let me know if I missed something and the problem is different, but I think this is fixed with the latest commit.

**Comment by Narice** [comment]
yup! works perfectly ;)
I will continue the installation and if I have anything else I'll report it, let's polish this v1 :sparkles:

**Comment by Pacman99** [comment]
>  I will continue the installation and if I have anything else I'll report it, let's polish this v1 sparkles

That would be amazing!! Thank you for all the information you have given us so far :)

**Comment by Narice** [comment]
No problem xD I get a wonderful system as compensation :p

**Comment by blaggacao** [comment]
And we seem to gain a wonderful new contributor! Welcome! Let's grow this little baby and as @nxrdp once said: "Let's fix this mess once and for all [around how NixOS is set up]" :+1:

**Comment by Narice** [comment]
Thanks!
