### ISSUE TITLE
Precise in the documentation that one can add the nrdxp cache with sudo if the current user is not trusted

### ISSUE THREAD

**Issue by Narice** [divnix/devos#292]
Precise in the documentation that one can add the nrdxp cache with sudo if the current user is not trusted.
This is related to this issue: #287.

**Comment by Pacman99** [comment]
That could be a good change for one of the guides in the `start` section.

**Comment by blaggacao** [comment]
> Precise in the documentation that one can add the nrdxp cache with sudo if the current user is not trusted.

For posterity and context, I link https://github.com/divnix/devos/issues/98 which expands on the possible future of cache configuration within the context of flakes (`nixConfiguration.subsituters`). That seems not yet working properly.

**Comment by Narice** [comment]
here it is!
I didn't resolve #98 with this one, to resolve it I think that a note should probably be made but in another file talking about configuration or an annex with things that do not work as of now if at all necessary
