### ISSUE TITLE
Cachix timeouts + how to disable nrdxp cachix (if needed)

### ISSUE THREAD

**Issue by kraft-nix** [divnix/devos#294]
## Expected Behavior
I am not sure whether https://cachix.org/ is having issues, but for the last day I have been unable to deploy any configurations due to a timeout issue:
```
❯ deploy ".#server-vm" --skip-checks --ssh-user operator --hostname 192.168.122.151 --debug-logs -- --show-trace
🚀 ❓ [deploy] [DEBUG] Checking for flake support
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
warning: Git tree '/home/kraftnix/config' is dirty
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[server-vm.system]
user = "root"
ssh_user = "operator"
path = "/nix/store/1xpf06zym5fx66wrqymqv98b1h87i62s-activatable-nixos-system-server-vm-21.05.20210516.779a569"
hostname = "server-vm"
ssh_opts = []

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `server-vm`
warning: Git tree '/home/kraftnix/config' is dirty
🚀 ❓ [deploy] [DEBUG] Copying profile `system` to node `server-vm`
warning: error: unable to download 'https://nrdxp.cachix.org/nix-cache-info': Timeout was reached (28); retrying in 296 ms
warning: error: unable to download 'https://nrdxp.cachix.org/nix-cache-info': Timeout was reached (28); retrying in 574 ms
```

## Current Behavior

When this happens I would like to be able to disable `cachix` caches and do a full build on my local system so I can continue to work. Looking at [the docs](https://devos.divnix.com/integrations/cachix.html) I should be able to remove/comment out the caches in `profiles/cachix/nrdxp.nix`, run a rebuild and then it should be disabled.

However even after doing this I am still getting connection issues trying to connect to https://nrdxp.cachix.org

## Possible Solution
Allow users to disable cachix, provide documentation for how to do so.

## Context

I currently cannot deploy new builds at all.

I can access https://nrdxp.cachix.org from my browser and curl/wget.

## Your Environment

Fork of `devos` from release [v0.9.0](https://github.com/divnix/devos/releases/tag/v0.9.0)

**Comment by Pacman99** [comment]
Thank you for reporting this!

The situation with cachix and most auto-imports is much better in the latest core(soon to be 0.10.0).

In v0.9.0 we still imported cachix inside lib, so its harder to remove, you have to remove this line: https://github.com/divnix/devos/blob/9eeddb8dacff9a5f6f4ec2645247160c074aaca3/lib/devos/mkHosts.nix#L66.

But I would really recommend updating to the latest core, since there you can just remove a line from the core profile and drop the cachix profile.

**Comment by kraft-nix** [comment]
This did work for me, thanks.

I used regularly merge in changes directly from `core`, but I got bitten a few times and lost days worth of time debugging (with issues like ca-derivations) and with the ever-changing API I ended up spending too much time keeping up to date with `devos` instead of doing the work I needed to do. On that note I'm looking forward to the stable API / v1.0
