### ISSUE TITLE
Adapt gitignore to recent build commants imporovements

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#305]
There have been recent improvement on `digga` to the build command so they are created not under `./result` but in more user friendly places, like `./iso` or `./vm`.

To avoid accidentally commiting big blobs, update the gitignore here.

/cc @Narice

**Comment by Pacman99** [comment]
just updated them in https://github.com/divnix/devos/commit/30892d83eb9461b1249a7b392eedb21cd2c38e3e
