### ISSUE TITLE
pkgs in home-manager profiles

### ISSUE THREAD

**Issue by Radvendii** [divnix/devos#309]
## Would your feature fix an existing issue?
not that i'm aware of

## Describe the solution you'd like
just like in system profiles, i want to be able to take in `pkgs` (and possibly other things like `config` in home-manager profiles. .

## Describe alternatives you've considered
I can't think of another easy way to get things where they need to go.

## Additional context
There are some attributes that require packages as values, or commands that require something like `${pkgs.feh}/bin/feh` to work

**Comment by Pacman99** [comment]
Home-manager profiles are just like any other module, you can get pkgs as an argument.
```
{ config, pkgs, ... }:
{
  environment.systemPackages = [ pkgs.feh ];
}
```

If that doesn't work, then there's a bug or perhaps I'm misunderstanding the question.

**Comment by Radvendii** [comment]
Oh, you're totally right. I tried it and it seemed to break, but now it's working. I guess I did something else wrong.
