### ISSUE TITLE
replacing and disabling modules with new api

### ISSUE THREAD

**Issue by almostnobody** [divnix/devos#310]
[In the docs there is a:](https://devos.divnix.com/concepts/overrides.html)
>You can also pull modules from other channels. All modules have access to the modulesPath for each channel as <channelName>ModulesPath. And you can use disabledModules to remove modules from the current channel.
>
>Pulling the zsh module from the latest channel:
> ```nix
> { latestModulesPath }: {
>   modules = [ "${latestModulesPath}/programs/zsh/zsh.nix" ];
>   disabledModules = [ "programs/zsh/zsh.nix" ];
> }
> 
> ```

but it's unclear where it is supposed to be put/used

I'm filing it as a bug, since it's an issue with docs, but i would appreciate the advice, and willing to fix the docs

**Comment by almostnobody** [comment]
my personal issue is that i want to add a module from a specific channel to a specific host(exclusively that host)

**Comment by almostnobody** [comment]
turns out it's a regular nix code
```nix
{ latestModulesPath }: {
  import = [ "${latestModulesPath}/programs/zsh/zsh.nix" ];
  disabledModules = [ "programs/zsh/zsh.nix" ];
}
```
this kind of code works, not sure if it's the right way, and if the docs should be updated to make it more clear for newcomers

**Comment by Pacman99** [comment]
Agreed thanks for opening this. The first issue is the docs should use `imports`, I messed that up. And the next issue is that the docs need to be more explicit that module overriding can happen in any module, whether its your host file, a profile, or a module in ./modules.
