### ISSUE TITLE
Docs: relation between agenix / git-crypt

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#314]
This motion suggests clarifying the docs (git-crypt: 'legacy'):

https://github.com/divnix/devos/discussions/185#discussioncomment-851296

We could also deprecate it alltogether.

We should have a discussion if we have a need for (git clean / smudge) implementation, that is, if that's desired or rather harmful.

/cc @cipharius

**Comment by Pacman99** [comment]
Actually I would say just remove it all together in the develop branch, so next time we update core its gone. Maybe add a note to the docs that we used to use git-crypt but have now fully switched to agenix.

**Comment by Pacman99** [comment]
git-crypt is now removed entirely.
