### ISSUE TITLE
Add upstream issue tracker

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#320]
Add an `UpstreamIssues.md` at the root issue to have a handy reference and index with relevant issues.

We can quickly accept PRs with known upstream issues and help people discover them.

But people might also use it to document and track their upstream / todo issues with us.

/cc @Narice (thanks for the idea)

**Comment by Pacman99** [comment]
Why not use github issues and just label certain issues as "upstream"? Or if your concerned about opening issues we can't directly fix, then we could open one "wiki" issue to post the upstream bugs.
I don't like having a markdown doc in-tree because adding new issues requires PRs or commits and github already solves this for us with github issues.

**Comment by blaggacao** [comment]
I think the fringe benefit of some sort of Markdown is that users have an _intuitive_ place to research and document their issues locally in-tree. I think using unstable features it might be also helpful to have issues documented present in any given commit. @Narice Maybe you can complement? I was inferring that +- from your suggestion.

**Comment by blaggacao** [comment]
I agree, we should probably just fix them instead of documenting... :+1:

**Comment by Narice** [comment]
> I think the fringe benefit of some sort of Markdown is that users have an _intuitive_ place to research and document their issues locally in-tree. I think using unstable features it might be also helpful to have issues documented present in any given commit. @Narice Maybe you can complement? I was inferring that +- from your suggestion.

sorry I didn't read that before today :smile:, having a tag for it is fine :wink:

**Comment by blaggacao** [comment]
We now have even an "Upstream" issue tempalte :smile:
