### ISSUE TITLE
Support aarch64-darwin 

### ISSUE THREAD

**Issue by liaowang11** [divnix/devos#335]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Describe the solution you'd like
Define `aarch64-darwin` system doesn't work for now, I get 
```
A definition for option `nixos.hosts.mbp-m1.system' is not of type `system defined in `supportedSystems`'.
```

But I cannot find supportedSystems defined any where in `digga` or `devos`, maybe it's from nixpkgs?

```nix
        hosts = {
          "mbp-m1" = {
            system = "aarch64-darwin";
          };
        };

```

## Describe alternatives you've considered
For now, only have to manually import pkgsM1 to use any native packages.

```nix
  pkgsM1 = import <nixpkgs> { localSystem = "aarch64-darwin"; };
```

**Comment by Pacman99** [comment]
`supportedSystems` is a top-level argument in digga. It can be set in your flake.nix, just add a `supportedSystems = [ ... ]` line anywhere inside the attribute set thats passed to `mkFlake`.

**Comment by blaggacao** [comment]
Th default comes al the way from: https://github.com/numtide/flake-utils/blob/f7e004a55b120c02ecb6219596820fcd32ca8772/default.nix#L3-L8

**Comment by liaowang11** [comment]
> `supportedSystems` is a top-level argument in digga. It can be set in your flake.nix, just add a `supportedSystems = [ ... ]` line anywhere inside the attribute set thats passed to `mkFlake`.

Works like a charm.
Is there any way in digga I can define two pkgs(one for native and one for x86_64-darwin) to pass to my m1 host config? I have to use `--impure` to build `homeConfigurations`.

**Comment by blaggacao** [comment]
> Is there any way in digga that I can define two nixpkgs(one for native and one for x86_64-darwin) to pass to my m1 host config? I have to use --impure to build homeConfigurations.

Could you clarify what you are trying to do? Do you want to have different `{pkgs, ... }` as module inputs? Something doesn't sound right, though. Or most probably: I'm missing most of the context.

**Comment by liaowang11** [comment]
> > Is there any way in digga that I can define two nixpkgs(one for native and one for x86_64-darwin) to pass to my m1 host config? I have to use --impure to build homeConfigurations.
> 
> Could you clarify what you are trying to do? Do you want to have different `{pkgs, ... }` as module inputs? Something doesn't sound right, though. Or most probably: I'm missing most of the context.

Yes, I wish to have something like `{pkgs, pkgsM1, ...}`. As some package are still not working under `aarch64-darwin`, I would like to use `pkgsM1` for packages that are working natively and `pkgs` for some package like `ghc`.

What I do to archive this for now is just importing another `pkgs` on top of every module file, which looks ugly and cannot use `devos packages` defined in `pkgs` folder.
```
pkgsX86 = import <nixpkgs> { localSystem = "x86_64-darwin"; };
```
