### ISSUE TITLE
After implementation of digga's `rakeLeaves`, can't rebuild in the presence of `*/modules-list.nix`

### ISSUE THREAD

**Issue by cipharius** [divnix/devos#351]
## Expected Behavior
Rebuild without errors after flake update.

## Current Behavior
I get an undescriptive error originating from nixpkgs repository. It might be related to my setup, but the error doesn't really help finding the reason it's broken. Tested both `core` and `develop` branches, both don't work.

Also, `core` branch has incorrect url to digga main branch, as it refers to non-existing `master` branch.

The error in question:

```
error: value is a list while a set was expected

       at /nix/store/m35mc9chdjl73yk17vcn4bsidngxqzky-source/lib/modules.nix:285:44:

          284|         options = {};
          285|         config = addFreeformType (addMeta (removeAttrs m ["_file" "key" "disabledModules" "require" "imports" "freeformType"]));
             |                                            ^
          286|       };
(use '--show-trace' to show detailed location information)
```

the store path leads to nixpkgs deriviation.

## Steps to Reproduce
1. `nix develop`
2. `bud rebuild HOST switch`

## Your Environment
My devos repository: https://github.com/cipharius/devos

**Comment by blaggacao** [comment]
`m` here refers to a _module_, which for some reason appears to be a list. You'd have to look a little further up the trace stack to see where the offending value is actually coming from.

If you wish to publish the stactrace on e.g. 0x0.st I could try to help you analyze it.

> Also, core branch has incorrect url to digga main branch, as it refers to non-existing master branch.

Thanks for the the note. I'll fix that asap.

**Comment by cipharius** [comment]
Here, I uploaded the whole stack trace: http://0x0.st/-WnO.txt

**Comment by blaggacao** [comment]
Ok that didn't reveal much. :confused: Did you try to run `devos/core` with latest `digga/main`? That is probably not going to work.

Maybe we should pin core to a specific known working digga commit until we are able to merge develop back into `core`...

**Comment by cipharius** [comment]
I was originally on core and switched to develop in hopes that the misterious issue would be resolved there.

I've tried changing nixpkgs source from release to master, but I get the same error.

**Comment by blaggacao** [comment]
Ah, so it looks like you didn't resolve a merge conflict in the sense of the new digga `lib.importModules`. [this file](https://www.github.com/cipharius/devos/tree/cipharius/modules%2Fmodule-list.nix) would be interpreted as a module via `lib.importModules`'s use of `lib.rakeLeaves`.

**Comment by blaggacao** [comment]
I hope this commit would have been able to hint appropriately and within context would it have been available before https://github.com/divnix/devos/commit/5bd943f97da8e63c4b8a6c234d71fcdb7b7e7193

**Comment by cipharius** [comment]
Good catch!

Yeah, file deletion was a subtle conflict during merge alongsides more obvious conflicts, this notice would have helped.
But in general, I think switch to more consistent rakeLeaves approach is an important change.

Removing the `modules-list.nix` file does fix the issue, thank you!
