### ISSUE TITLE
Docs site contains inconsistent references to both `flk` and `bud`

### ISSUE THREAD

**Issue by montchr** [divnix/devos#366]
I haven't yet got up and running with DevOS, and part of the reason for that was some contradictions in the documentation site.

For example, "Quick Start" references the `core` branch and `flk`, while the next "ISO" page references `bud`, and the "From NixOS" page after that refers to `flk` again.

### Discussed in https://github.com/divnix/devos/discussions/361

<div type='discussions-op-text'>

<sup>Originally posted by **cwhy** September 14, 2021</sup>
Hi I am new to NixOS and want to try a friendly setup. I am quite confused at this page, which is a essential page for setup the system: `https://devos.divnix.com/start/iso.html`. The page requires me to install `bud` but I see no documentation for how to install `bud` from `https://devos.divnix.com/bud/index.html` or the repo.

Any help?
Thanks~</div>

**Comment by montchr** [comment]
I would gladly open a pull request, but I'm not sure how to proceed – is there a guide somewhere for the project's branching/release workflow? Is the guide (on GitHub Pages) supposed to reference the state of things on `core` or `master`?

**Comment by nrdxp** [comment]
Very sorry about this. The DevOS docs are getting to be quite stale and I haven't had time to update them. I thought we did away with core entirely. The latest state of development should be master.

**Comment by montchr** [comment]
It's all good, thanks for the clarification. For this particular thing on the quick start page, I can open a PR to update the reference if that would be helpful.

**Comment by nrdxp** [comment]
yes that'd be great, documentation PRs are greatly appreciated :slightly_smiling_face:
