### ISSUE TITLE
Primary branch name in CI configurations points to `main` but `main` was renamed to `master`

### ISSUE THREAD

**Issue by montchr** [divnix/devos#369]
## Expected Behavior

CI workflow configurations and documentation should reference the current primary branch. At this point in time, that is `master`, but ideally `master` would be removed in favor of a  `main` branch as the primary branch on GitHub.

## Current Behavior

There are still [a few references](https://github.com/divnix/devos/search?q=main) throughout the project to `main`, which appears to have been renamed to `master` (see #368).

The primary result of this is that CI workflows are not running upon pushes to `master` as they had been for `main`.

## Possible Solution

Rename `master` to `main` if currently feasible.

If not currently feasible, replace references to `main` with `master` to reflect the repo's current state until `master` can be renamed to `main` in line with conventions and the previous state of the repo.

## Steps to Reproduce

Most notably `main` is left over in some CI configurations:

https://github.com/divnix/devos/blob/a3b2bcf3d57be28c27119a44445cfdde38349cb9/.github/workflows/mdbook_docs.yml#L1-L6

https://github.com/divnix/devos/blob/a3b2bcf3d57be28c27119a44445cfdde38349cb9/.github/workflows/check.yml#L1-L7

`main` is also referred to as the preferred base branch for pull requests in https://github.com/divnix/devos/blob/master/doc/CONTRIBUTING.md 

## Context

I'm guessing this explains not only why the live docs site is out of sync with `master` but also why checks and Cachix update workflows haven't been running.

It might also be the cause of #363 since 079adc4474231d5582fee5574bc5bcc6f133e5ac was the last commit to cause that workflow run.

**Comment by blaggacao** [comment]
Great Analysis! Thx!

**Comment by montchr** [comment]
Sounds good, thank you. I think #371 sufficiently addresses the issue in that case. Actions are running again! I'll close this out.
