### ISSUE TITLE
Encrypt with (r)age

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#37]
**Is your feature request related to a problem? Please describe.**
I finally want to use [age](https://github.com/FiloSottile/age) / [rage](https://github.com/str4d/rage).

**Describe the solution you'd like**

Something around those lines... (not well thought through)
```
secrets/** filter=crypt
[filter "crypt"]
	clean = rage -r $(cat ~/.ssh/id_ed25519.pub)
	smudge = rage --decrypt -i ~/.ssh/id_ed25519
	required
```

**Describe alternatives you've considered**
none / sops, but sops has ugly configmgt domain overlap with nix.

**Additional context**

https://git-scm.com/docs/gitattributes

**Comment by nrdxp** [comment]
I've been exploring possibly integrating [agenix](https://github.com/ryantm/agenix) support, so that we can store encrypted secrets properly. More experimentation is needed.

**Comment by FlorianFranzen** [comment]
I currently use [`git-crypt`](https://www.agwa.name/projects/git-crypt/) which works well for my use case.

**Comment by adrian-gierakowski** [comment]
> ugly configmgt domain overlap with nix

@blaggacao I’m curious what you meant by this. Would you be able to elaborate? Thanks!

**Comment by blaggacao** [comment]
Sure. Its direct manifestation is that sops has a separate yaml config file. I really like the agenix idea since it keeps the configuration domain within the (the power of the) nix language entirely.

**Comment by nrdxp** [comment]
Personally, I'd just like to have secrets that aren't world readable. I'll still probably keep git crypt available even if we do add support for agenix since they address separate concerns, i.e:

git-crypt -> protects secrets stored in the repo
agenix -> protects secrets deployed to nix-store

Of course, I still have to experiment with agenix to see how well it delivers on this promise.

**Comment by blaggacao** [comment]
I [researched a little](https://github.com/ryantm/agenix/issues/11#issuecomment-751931051). I seems at least conceivable in principle that agenix can extend its scope to support the git crypt use case in an unified way.

**Comment by blaggacao** [comment]
https://github.com/ryantm/agenix/pull/12

**Comment by blaggacao** [comment]
please, if anyone feels (more) competent / confident than me, take over: https://github.com/ryantm/agenix/pull/14

**Comment by blaggacao** [comment]
There has been made an important argument [here](https://github.com/ryantm/agenix/pull/14#issuecomment-752254610):
> Unless we can come up with some better plan for how to import the files into the NixOS configuration, they need to be encrypted at rest.

meaning `git.filter.agenix.smudge` and `git.filter.agenix.clean` are vetoed for the time being (agenix has `agenix --edit <file>` for the remainder of the use case), leaving us with `git.filter.agenix.textconv` &mash; yaay!

**Comment by ymarkus** [comment]
Is there any progress with secrets? I don't really care how it's done, but I would really like a solution integrated in this template. I've thought about doing something like [sops-nix](https://github.com/Mic92/sops-nix) or something with pass?

**Comment by nrdxp** [comment]
@ymarkus, unfortunately not, but it's on the agenda. After reviewing the options, my prefered solution would use gopass, but I've yet to work out all the details. I'll have more time this month than last, so hopefully we can get this knocked out soon.

**Comment by codygman** [comment]
I don't quite understand this statement:

>  sops has ugly configmgt domain overlap with nix.

I was just investigating sops-nix after having lots of issues with git-crypt (maybe because I'm using an ed25519 gpg key) and it seemed like the most convenient option here.

I'm not sure how a gopass based solution might work though.

**Comment by Pacman99** [comment]
Personal opinion: devos shouldn't include secrets management, outside of git-crypt - just to protect new users. 

secrets management is a very wide concern and everyone has different requirements. And with the extern folder, its really easy to set up stuff yourself. I was able to use agenix with my server, by just adding the input then the module in extern. Then I just followed agenix instructions with creating a secrets.nix file in the secrets folder. 

What could be useful is maybe adding documentation on how to integrate different secrets management tools with devos.

**Comment by blaggacao** [comment]
> I don't quite understand this statement:

> >    sops has ugly configmgt domain overlap with nix.


This question actually came up before. Expanding on my [previous reply]((https://github.com/divnix/devos/issues/37#issuecomment-751414379)): from the asciinema animation on the github repo:

> `SOPS encrypts the values of a yaml or json file not the keys.`

Hence, the tool was designed to do work as a function of an **authoritative** yaml/json file.

I think devops tries to put all (core) configuration management under the domain of the nix (later maybe nickel) language. Insofar sops appears a bit incompatible with this repository's goals and philosophy.

**Comment by nrdxp** [comment]
@blaggacao, I agree. I looked at sops and it didn't seem appealing for this project. Honestly, none of the options are absolutely ideal, and I keep wondering why Nix hasn't solved this problem by now, as it was one of the earliest issues opened on the GitHub tracker, some 9 years ago. I must be missing something important, because changing permissions inside the nix store, or perhaps having a separate nix/secret-store with secure permissions doesn't seem like it should be all that difficult.

Alas...

**Comment by blaggacao** [comment]
https://github.com/FiloSottile/age/releases/tag/v1.0.0-rc.1 (breaking news :smile_cat: )

**Comment by blaggacao** [comment]
Thought fodder:

- https://christine.website/blog/nixos-encrypted-secrets-2021-01-20

/cc @Xe
