### ISSUE TITLE
[nixpkgs]: nix-direnv no longer needs override

### ISSUE THREAD

**Issue by blm768** [divnix/devos#415]
## Link
[Merged PR](https://github.com/NixOS/nixpkgs/pull/145236)

## Context
It looks like `nix-direnv` now has flake support without the `nix` option, so once we pull in a newer NixOS version, the override in `overlays/overrides.nix` won't be necessary (and in fact produces an evaluation error).

**Comment by Pacman99** [comment]
Done in #422
