### ISSUE TITLE
incomplete substituters file

### ISSUE THREAD

**Issue by benneti** [divnix/devos#98]
**Describe the bug**
I think the incompleteness of 
`  nixConfig.substituters = [ "https://nrdxp.cachix.org" ];`
confuses nix, I follow nixos-unstable with my pkgs and had to add
```
# add links for binary caches here
  nixConfig.substituters = [
    "https://cache.nixos.org/"
    "https://nrdxp.cachix.org"
    "https://nix-community.cachix.org"
  ];
```
to again use the binary cache.

**To Reproduce**
Use flakes
1. maybe switch to `nixos.url = "nixpkgs/nixos-unstable";`
2. rebuild system

**To Fix**
add
```
  nixConfig.substituters = [
    "https://cache.nixos.org/"
    "https://nrdxp.cachix.org"
    "https://nix-community.cachix.org"
  ];
```
**Expected behavior**
have completer substituters (or none?).
Also I am a bit confused, do we still rely on the cachix configuration -- if not I think it should be deleted for it to be less confusing.

I think this PR is related: https://github.com/nrdxp/nixflk/pull/71.

**Comment by nrdxp** [comment]
After reviewing upstream, this config isn't even sent to the daemon yet. Once it is, we should unify the nix.conf everywhere using this mechanism, but for now it's causing issues with no benefit and should simply be reverted.
https://github.com/NixOS/nix/commit/343239fc8a1993f707a990c2cd54a41f1fa3de99#diff-3a977e1e533a3b628a371bf19103f87d5501dc35df5fb1142551a9896cf3b03aR539

**Comment by Pacman99** [comment]
Closing this, I believe substituters in nixConfig and cachix profile are good to go. Feel free to re-open if this still needs some work.
